# Site wide configuration

title:            Luis D. Verde Arregoitia
locale:           en_US
url:              http://luisdva.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-feed
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Luis Verde Arregoitia
  description: ecology.evolution.conservation.biogeography
  avatar: https://pbs.twimg.com/profile_images/800225437343301632/n-A0uKfw.jpg
  bio: "Personal research page - 
  ecology . evolution . conservation . biogeography"
  email: 
  disqus-shortname: 
  twitter: LuisDVerde
  facebook: #username
  google:
    plus: #username
    analytics: UA-65540014-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: #username
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  publons: 980996
  researchgate: Luis_Verde_Arregoitia
  gscholar: Ii0dP6kAAAAJ

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

